

# #+RESULTS: add stable helm repo
# #+begin_example
# "stable" has been added to your repositories
# #+end_example


# #+name: nginx ingress values

---
controller:
  service:
    externalTrafficPolicy: Local
    type: LoadBalancer
  publishService:
    enabled: true
  config:
    service-tokens: "false"
    use-proxy-protocol: "false"
    compute-full-forwarded-for: "true"
    use-forwarded-headers: "true"
  metrics:
    enabled: true
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10

serviceAccount:
  create: true

rbac:
  create: true
