apiVersion: v1
kind: ServiceAccount
metadata:
  name: verify-conformance-ci
  namespace: prow
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: verify-conformance-ci
  namespace: prow
rules:
  - apiGroups:
      - apps/v1
    resources:
      - deployments
    verbs:
      - get
      - list
      - update
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: verify-conformance-ci
  namespace: prow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: verify-conformance-ci
subjects:
  - name: verify-conformance-ci
    namespace: prow
    kind: ServiceAccount
