defaultBaseImage: ghcr.io/cncf-infra/prow-config/base-image
builds:
  - id: verify-conformance-release
    dir: .
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -tags
      - netgo
    ldflags:
      - -s -w
      - -extldflags "-static"
